# Exploração - Censo Escolar - Turma

**OBJETIVOS**: Explorar a base de Turma do censo escolar e fazer o rascunho do processamento de dados

---

## Cabeçalho

### Imports

In [1]:
import os
import pyunpack
import rarfile
import shutil
import zipfile
import numpy as np
import pandas as pd

from pathlib import Path
from tqdm import tqdm

### Caminhos

In [2]:
PASTA_PROJETO = Path("C:/Users/pedro.forli/PycharmProjects/curso-ciencia-dados")
PASTA_DADOS = PASTA_PROJETO / "dados"
PASTA_SAIDA = PASTA_PROJETO / "saidas"
PASTA_NOTEBOOK = PASTA_PROJETO / "notebooks"
os.chdir(PASTA_PROJETO)

### Variáveis

### Configurações

In [3]:
%config Completer.use_jedi = False
%load_ext autoreload
%autoreload 2

### Código Próprio

In [4]:
import src.io.le_dados as le_dados
import src.io.caminho as caminho
import src.io.data_store as data_store

---

## Carregamento de Dados

In [5]:
os.chdir(PASTA_PROJETO)
dados = {
    f: le_dados.le_dados_comprimidos(
        f"dados/completo/externo/censo_escolar/{f}",
        ext="zip",
        como_df=True,
        padrao_comp="(turmas|TURMAS|Turmas)[.](csv|CSV|rar|RAR|zip|ZIP)",
        sep="|",
        encoding="latin-1",
    )
    for f in os.listdir("dados/completo/externo/censo_escolar")
}
dados = {k: v for k, v in dados.items() if v is not None}

---

## Exploração

Visualiza como os dados aparecem na base

In [6]:
dados["2020.zip"].head()

,NU_ANO_CENSO,ID_TURMA,NO_TURMA,TP_MEDIACAO_DIDATICO_PEDAGO,TX_HR_INICIAL,TX_MI_INICIAL,IN_DIA_SEMANA_DOMINGO,IN_DIA_SEMANA_SEGUNDA,IN_DIA_SEMANA_TERCA,IN_DIA_SEMANA_QUARTA,...,IN_MANT_ESCOLA_PRIVADA_EMP,IN_MANT_ESCOLA_PRIVADA_ONG,IN_MANT_ESCOLA_PRIVADA_OSCIP,IN_MANT_ESCOLA_PRIV_ONG_OSCIP,IN_MANT_ESCOLA_PRIVADA_SIND,IN_MANT_ESCOLA_PRIVADA_SIST_S,IN_MANT_ESCOLA_PRIVADA_S_FINS,TP_REGULAMENTACAO,TP_LOCALIZACAO_DIFERENCIADA,IN_EDUCACAO_INDIGENA
0,2020,146,6º ANO TARDE,1,13.0,0.0,0.0,1.0,1.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,0
1,2020,160,7º ANO MANHA,1,7.0,0.0,0.0,1.0,1.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,0
2,2020,177,INFANTIL II - TARDE,1,13.0,0.0,0.0,1.0,1.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,0
3,2020,202,2º ANO C ALFABETIZAR COM SUCESSO,1,7.0,30.0,0.0,1.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,0
4,2020,205,4º ANO B DO ALFABETIZAR COM SUCESSO,1,12.0,45.0,0.0,1.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,0

In [7]:
dados["2020.zip"].tail()

,NU_ANO_CENSO,ID_TURMA,NO_TURMA,TP_MEDIACAO_DIDATICO_PEDAGO,TX_HR_INICIAL,TX_MI_INICIAL,IN_DIA_SEMANA_DOMINGO,IN_DIA_SEMANA_SEGUNDA,IN_DIA_SEMANA_TERCA,IN_DIA_SEMANA_QUARTA,...,IN_MANT_ESCOLA_PRIVADA_EMP,IN_MANT_ESCOLA_PRIVADA_ONG,IN_MANT_ESCOLA_PRIVADA_OSCIP,IN_MANT_ESCOLA_PRIV_ONG_OSCIP,IN_MANT_ESCOLA_PRIVADA_SIND,IN_MANT_ESCOLA_PRIVADA_SIST_S,IN_MANT_ESCOLA_PRIVADA_S_FINS,TP_REGULAMENTACAO,TP_LOCALIZACAO_DIFERENCIADA,IN_EDUCACAO_INDIGENA
2353346,2020,21849427,AEE MANHA,1,8.0,0.0,0.0,1.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,0
2353347,2020,21850426,AEE TARDE,1,12.0,30.0,0.0,1.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,0
2353348,2020,21850427,AEE-1,1,7.0,0.0,0.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,0
2353349,2020,21850428,AEE-2,1,13.0,0.0,0.0,0.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,0
2353350,2020,21850429,AEE TARDE,1,14.0,0.0,0.0,1.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,0

In [8]:
dados["2020.zip"].sample(5)

,NU_ANO_CENSO,ID_TURMA,NO_TURMA,TP_MEDIACAO_DIDATICO_PEDAGO,TX_HR_INICIAL,TX_MI_INICIAL,IN_DIA_SEMANA_DOMINGO,IN_DIA_SEMANA_SEGUNDA,IN_DIA_SEMANA_TERCA,IN_DIA_SEMANA_QUARTA,...,IN_MANT_ESCOLA_PRIVADA_EMP,IN_MANT_ESCOLA_PRIVADA_ONG,IN_MANT_ESCOLA_PRIVADA_OSCIP,IN_MANT_ESCOLA_PRIV_ONG_OSCIP,IN_MANT_ESCOLA_PRIVADA_SIND,IN_MANT_ESCOLA_PRIVADA_SIST_S,IN_MANT_ESCOLA_PRIVADA_S_FINS,TP_REGULAMENTACAO,TP_LOCALIZACAO_DIFERENCIADA,IN_EDUCACAO_INDIGENA
2033641,2020,21330176,243899663 1006 ENFERMAGEM 2 MODULO 09 NOITE ANUAL,1,19.0,0.0,0.0,1.0,1.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,0
1088302,2020,19340481,EDUCACAO INFANTIL 1º PERIODO,1,7.0,0.0,0.0,1.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,0
1283666,2020,19557917,240604348 8 ANO B TARDE ANUAL,1,13.0,0.0,0.0,1.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,0
520583,2020,17483845,2º ANO - A,1,7.0,30.0,0.0,1.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,0
1990683,2020,21276354,244754503 4 ANO B TARDE ANUAL,1,13.0,10.0,0.0,1.0,1.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,0

In [26]:
dados["2020.zip"][dados["2020.zip"]["IN_REGULAR"].notnull()]

,NU_ANO_CENSO,ID_TURMA,NO_TURMA,TP_MEDIACAO_DIDATICO_PEDAGO,TX_HR_INICIAL,TX_MI_INICIAL,IN_DIA_SEMANA_DOMINGO,IN_DIA_SEMANA_SEGUNDA,IN_DIA_SEMANA_TERCA,IN_DIA_SEMANA_QUARTA,...,IN_MANT_ESCOLA_PRIVADA_EMP,IN_MANT_ESCOLA_PRIVADA_ONG,IN_MANT_ESCOLA_PRIVADA_OSCIP,IN_MANT_ESCOLA_PRIV_ONG_OSCIP,IN_MANT_ESCOLA_PRIVADA_SIND,IN_MANT_ESCOLA_PRIVADA_SIST_S,IN_MANT_ESCOLA_PRIVADA_S_FINS,TP_REGULAMENTACAO,TP_LOCALIZACAO_DIFERENCIADA,IN_EDUCACAO_INDIGENA
0,2020,146,6º ANO TARDE,1,13.0,0.0,0.0,1.0,1.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,0
1,2020,160,7º ANO MANHA,1,7.0,0.0,0.0,1.0,1.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,0
2,2020,177,INFANTIL II - TARDE,1,13.0,0.0,0.0,1.0,1.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,0
3,2020,202,2º ANO C ALFABETIZAR COM SUCESSO,1,7.0,30.0,0.0,1.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,0
4,2020,205,4º ANO B DO ALFABETIZAR COM SUCESSO,1,12.0,45.0,0.0,1.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2353322,2020,21847428,MATERNAL 1,1,7.0,30.0,0.0,1.0,1.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,0
2353323,2020,21847429,PRE 1,1,7.0,30.0,0.0,1.0,1.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,0
2353325,2020,21847431,3º ANO B TARDE,1,13.0,0.0,0.0,1.0,1.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,0
2353328,2020,21847434,1º ANO,3,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1,0,0
2353329,2020,21847435,2º ANO,3,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1,0,0

In [23]:
dados["2020.zip"].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2353351 entries, 0 to 2353350
Data columns (total 79 columns):
 #   Column                          Dtype
---  ------                          -----
 0   NU_ANO_CENSO                    int64
 1   ID_TURMA                        int64
 2   NO_TURMA                        object
 3   TP_MEDIACAO_DIDATICO_PEDAGO     int64
 4   TX_HR_INICIAL                   float64
 5   TX_MI_INICIAL                   float64
 6   IN_DIA_SEMANA_DOMINGO           float64
 7   IN_DIA_SEMANA_SEGUNDA           float64
 8   IN_DIA_SEMANA_TERCA             float64
 9   IN_DIA_SEMANA_QUARTA            float64
 10  IN_DIA_SEMANA_QUINTA            float64
 11  IN_DIA_SEMANA_SEXTA             float64
 12  IN_DIA_SEMANA_SABADO            float64
 13  NU_DIAS_ATIVIDADE               float64
 14  NU_DURACAO_TURMA                float64
 15  TP_TIPO_ATENDIMENTO_TURMA       int64
 16  TP_TIPO_LOCAL_TURMA             float64
 17  CO_TIPO_ATIVIDADE_1             float64
 18  CO_TIPO_ATIVIDADE_2             float64
 19  CO_TIPO_ATIVIDADE_3             float64
 20  CO_TIPO_ATIVIDADE_4             float64
 21  CO_TIPO_ATIVIDADE_5             float64
 22  CO_TIPO_ATIVIDADE_6             float64
 23  TP_ETAPA_ENSINO                 float64
 24  CO_CURSO_EDUC_PROFISSIONAL      float64
 25  IN_ESPECIAL_EXCLUSIVA           float64
 26  IN_REGULAR                      float64
 27  IN_EJA                          float64
 28  IN_PROFISSIONALIZANTE           float64
 29  QT_MATRICULAS                   int64
 30  IN_DISC_LINGUA_PORTUGUESA       float64
 31  IN_DISC_EDUCACAO_FISICA         float64
 32  IN_DISC_ARTES                   float64
 33  IN_DISC_LINGUA_INGLES           float64
 34  IN_DISC_LINGUA_ESPANHOL         float64
 35  IN_DISC_LINGUA_FRANCES          float64
 36  IN_DISC_LINGUA_OUTRA            float64
 37  IN_DISC_LIBRAS                  float64
 38  IN_DISC_LINGUA_INDIGENA         float64
 39  IN_DISC_PORT_SEGUNDA_LINGUA     float64
 40  IN_DISC_MATEMATICA              float64
 41  IN_DISC_CIENCIAS                float64
 42  IN_DISC_FISICA                  float64
 43  IN_DISC_QUIMICA                 float64
 44  IN_DISC_BIOLOGIA                float64
 45  IN_DISC_HISTORIA                float64
 46  IN_DISC_GEOGRAFIA               float64
 47  IN_DISC_SOCIOLOGIA              float64
 48  IN_DISC_FILOSOFIA               float64
 49  IN_DISC_ESTUDOS_SOCIAIS         float64
 50  IN_DISC_EST_SOCIAIS_SOCIOLOGIA  float64
 51  IN_DISC_INFORMATICA_COMPUTACAO  float64
 52  IN_DISC_ENSINO_RELIGIOSO        float64
 53  IN_DISC_PROFISSIONALIZANTE      float64
 54  IN_DISC_ESTAGIO_SUPERVISIONADO  float64
 55  IN_DISC_PEDAGOGICAS             float64
 56  IN_DISC_OUTRAS                  float64
 57  CO_ENTIDADE                     int64
 58  CO_REGIAO                       int64
 59  CO_MESORREGIAO                  int64
 60  CO_MICRORREGIAO                 int64
 61  CO_UF                           int64
 62  CO_MUNICIPIO                    int64
 63  CO_DISTRITO                     int64
 64  TP_DEPENDENCIA                  int64
 65  TP_LOCALIZACAO                  int64
 66  TP_CATEGORIA_ESCOLA_PRIVADA     float64
 67  IN_CONVENIADA_PP                float64
 68  TP_CONVENIO_PODER_PUBLICO       float64
 69  IN_MANT_ESCOLA_PRIVADA_EMP      float64
 70  IN_MANT_ESCOLA_PRIVADA_ONG      float64
 71  IN_MANT_ESCOLA_PRIVADA_OSCIP    float64
 72  IN_MANT_ESCOLA_PRIV_ONG_OSCIP   float64
 73  IN_MANT_ESCOLA_PRIVADA_SIND     float64
 74  IN_MANT_ESCOLA_PRIVADA_SIST_S   float64
 75  IN_MANT_ESCOLA_PRIVADA_S_FINS   float64
 76  TP_REGULAMENTACAO               int64
 77  TP_LOCALIZACAO_DIFERENCIADA     int64
 78  IN_EDUCACAO_INDIGENA            int64
dtypes: float64(61), int64(17), object(1)
memory usage: 1.4+ GB

In [15]:
dados["2007.zip"].columns

Index(['ANO_CENSO', 'PK_COD_TURMA', 'NO_TURMA', 'HR_INICIAL',
       'HR_INICIAL_MINUTO', 'NU_DURACAO_TURMA', 'NUM_MATRICULAS',
       'FK_COD_MOD_ENSINO', 'FK_COD_ETAPA_ENSINO', 'FK_COD_CURSO_PROF',
       'FK_COD_TIPO_TURMA', 'ID_QUIMICA', 'ID_FISICA', 'ID_MATEMATICA',
       'ID_BIOLOGIA', 'ID_CIENCIAS', 'ID_LINGUA_LITERAT_PORTUGUESA',
       'ID_LINGUA_LITERAT_INGLES', 'ID_LINGUA_LITERAT_ESPANHOL',
       'ID_LINGUA_LITERAT_OUTRA', 'ID_ARTES', 'ID_EDUCACAO_FISICA',
       'ID_HISTORIA', 'ID_GEOGRAFIA', 'ID_FILOSOFIA', 'ID_ESTUDOS_SOCIAIS',
       'ID_INFORMATICA_COMPUTACAO', 'ID_PROFISSIONALIZANTE',
       'ID_DIDATICA_METODOLOGIA', 'ID_FUNDAMENTOS_EDUCACAO',
       'ID_DISC_ATENDIMENTO_ESPECIAIS', 'ID_DISC_DIVERSIDADE_SOCIO_CULT',
       'ID_OUTRAS_DISCIPLINAS_PEDAG', 'ID_LIBRAS', 'ID_OUTRAS_DISCIPLINAS',
       'PK_COD_ENTIDADE', 'FK_COD_ESTADO', 'SIGLA', 'FK_COD_MUNICIPIO',
       'ID_LOCALIZACAO', 'ID_DEPENDENCIA_ADM', 'DESC_CATEGORIA_ESCOLA_PRIVADA',
       'ID_CONVENIADA_PP', 'ID_MANT_ESCOLA_PRIVADA_EMP',
       'ID_MANT_ESCOLA_PRIVADA_ONG', 'ID_MANT_ESCOLA_PRIVADA_SIND',
       'ID_MANT_ESCOLA_PRIVADA_APAE', 'ID_DOCUMENTO_REGULAMENTACAO',
       'ID_LOCALIZACAO_DIFERENCIADA', 'ID_EDUCACAO_INDIGENA'],
      dtype='object')

In [22]:
dados["2008.zip"].columns

Index(['ANO_CENSO', 'PK_COD_TURMA', 'NO_TURMA', 'HR_INICIAL',
       'HR_INICIAL_MINUTO', 'NU_DURACAO_TURMA', 'NUM_MATRICULAS',
       'FK_COD_MOD_ENSINO', 'FK_COD_ETAPA_ENSINO', 'FK_COD_CURSO_PROF',
       'FK_COD_TIPO_TURMA', 'ID_VEZ_ATIVIDADE_COMPLEMENTAR',
       'FK_COD_TIPO_ATIVIDADE_1', 'FK_COD_TIPO_ATIVIDADE_2',
       'FK_COD_TIPO_ATIVIDADE_3', 'FK_COD_TIPO_ATIVIDADE_4',
       'FK_COD_TIPO_ATIVIDADE_5', 'FK_COD_TIPO_ATIVIDADE_6', 'ID_QUIMICA',
       'ID_FISICA', 'ID_MATEMATICA', 'ID_BIOLOGIA', 'ID_CIENCIAS',
       'ID_LINGUA_LITERAT_PORTUGUESA', 'ID_LINGUA_LITERAT_INGLES',
       'ID_LINGUA_LITERAT_ESPANHOL', 'ID_LINGUA_LITERAT_OUTRA', 'ID_ARTES',
       'ID_EDUCACAO_FISICA', 'ID_HISTORIA', 'ID_GEOGRAFIA', 'ID_FILOSOFIA',
       'ID_ESTUDOS_SOCIAIS', 'ID_INFORMATICA_COMPUTACAO',
       'ID_PROFISSIONALIZANTE', 'ID_DIDATICA_METODOLOGIA',
       'ID_FUNDAMENTOS_EDUCACAO', 'ID_DISC_ATENDIMENTO_ESPECIAIS',
       'ID_DISC_DIVERSIDADE_SOCIO_CULT', 'ID_OUTRAS_DISCIPLINAS_PEDAG',
       'ID_LIBRAS', 'ID_OUTRAS_DISCIPLINAS', 'PK_COD_ENTIDADE',
       'FK_COD_ESTADO', 'SIGLA', 'FK_COD_MUNICIPIO', 'ID_LOCALIZACAO',
       'ID_DEPENDENCIA_ADM', 'DESC_CATEGORIA_ESCOLA_PRIVADA',
       'ID_CONVENIADA_PP', 'ID_TIPO_CONVENIO_PODER_PUBLICO',
       'ID_MANT_ESCOLA_PRIVADA_EMP', 'ID_MANT_ESCOLA_PRIVADA_ONG',
       'ID_MANT_ESCOLA_PRIVADA_SIND', 'ID_MANT_ESCOLA_PRIVADA_APAE',
       'ID_DOCUMENTO_REGULAMENTACAO', 'ID_LOCALIZACAO_DIFERENCIADA',
       'ID_EDUCACAO_INDIGENA'],
      dtype='object')

In [16]:
dados["2009.zip"].columns

Index(['ANO_CENSO', 'PK_COD_TURMA', 'NO_TURMA', 'HR_INICIAL',
       'HR_INICIAL_MINUTO', 'NU_DURACAO_TURMA', 'NUM_MATRICULAS',
       'FK_COD_MOD_ENSINO', 'FK_COD_ETAPA_ENSINO', 'FK_COD_CURSO_PROF',
       'FK_COD_TIPO_TURMA', 'ID_VEZ_ATIVIDADE_COMPLEMENTAR',
       'FK_COD_TIPO_ATIVIDADE_1', 'FK_COD_TIPO_ATIVIDADE_2',
       'FK_COD_TIPO_ATIVIDADE_3', 'FK_COD_TIPO_ATIVIDADE_4',
       'FK_COD_TIPO_ATIVIDADE_5', 'FK_COD_TIPO_ATIVIDADE_6', 'ID_BRAILLE',
       'ID_AUTONOMA', 'ID_RECURSOS_BAIXA_VISAO', 'ID_PROCESSOS_MENTAIS',
       'ID_ORIENTACAO_MOBILIDADE', 'ID_SINAIS', 'ID_COM_ALT_AUMENT',
       'ID_ENRIQ_CURRICULAR', 'ID_SOROBAN', 'ID_INF_ACESSIVEL', 'ID_PORT_ESC',
       'ID_QUIMICA', 'ID_FISICA', 'ID_MATEMATICA', 'ID_BIOLOGIA',
       'ID_CIENCIAS', 'ID_LINGUA_LITERAT_PORTUGUESA',
       'ID_LINGUA_LITERAT_INGLES', 'ID_LINGUA_LITERAT_ESPANHOL',
       'ID_LINGUA_LITERAT_OUTRA', 'ID_LINGUA_LITERAT_INDIGENA', 'ID_ARTES',
       'ID_EDUCACAO_FISICA', 'ID_HISTORIA', 'ID_GEOGRAFIA', 'ID_FILOSOFIA',
       'ID_ENSINO_RELIGIOSO', 'ID_ESTUDOS_SOCIAIS',
       'ID_INFORMATICA_COMPUTACAO', 'ID_PROFISSIONALIZANTE',
       'ID_DISC_ATENDIMENTO_ESPECIAIS', 'ID_DISC_DIVERSIDADE_SOCIO_CULT',
       'ID_LIBRAS', 'ID_DISCIPLINAS_PEDAG', 'ID_OUTRAS_DISCIPLINAS',
       'PK_COD_ENTIDADE', 'FK_COD_ESTADO', 'SIGLA', 'FK_COD_MUNICIPIO',
       'ID_LOCALIZACAO', 'ID_DEPENDENCIA_ADM', 'DESC_CATEGORIA_ESCOLA_PRIVADA',
       'ID_CONVENIADA_PP', 'ID_TIPO_CONVENIO_PODER_PUBLICO',
       'ID_MANT_ESCOLA_PRIVADA_EMP', 'ID_MANT_ESCOLA_PRIVADA_ONG',
       'ID_MANT_ESCOLA_PRIVADA_SIND', 'ID_MANT_ESCOLA_PRIVADA_S_FINS',
       'ID_DOCUMENTO_REGULAMENTACAO', 'ID_LOCALIZACAO_DIFERENCIADA',
       'ID_EDUCACAO_INDIGENA'],
      dtype='object')

In [17]:
dados["2011.zip"].columns

Index(['ANO_CENSO', 'PK_COD_TURMA', 'NO_TURMA', 'HR_INICIAL',
       'HR_INICIAL_MINUTO', 'NU_DURACAO_TURMA', 'NUM_MATRICULAS',
       'FK_COD_MOD_ENSINO', 'FK_COD_ETAPA_ENSINO', 'FK_COD_CURSO_PROF',
       'FK_COD_TIPO_TURMA', 'ID_VEZ_ATIVIDADE_COMPLEMENTAR',
       'FK_COD_TIPO_ATIVIDADE_1', 'FK_COD_TIPO_ATIVIDADE_2',
       'FK_COD_TIPO_ATIVIDADE_3', 'FK_COD_TIPO_ATIVIDADE_4',
       'FK_COD_TIPO_ATIVIDADE_5', 'FK_COD_TIPO_ATIVIDADE_6', 'ID_BRAILLE',
       'ID_RECURSOS_BAIXA_VISAO', 'ID_PROCESSOS_MENTAIS',
       'ID_ORIENTACAO_MOBILIDADE', 'ID_SINAIS', 'ID_COM_ALT_AUMENT',
       'ID_ENRIQ_CURRICULAR', 'ID_SOROBAN', 'ID_INF_ACESSIVEL', 'ID_PORT_ESC',
       'ID_AUT_ESCOLAR', 'ID_QUIMICA', 'ID_FISICA', 'ID_MATEMATICA',
       'ID_BIOLOGIA', 'ID_CIENCIAS', 'ID_LINGUA_LITERAT_PORTUGUESA',
       'ID_LINGUA_LITERAT_INGLES', 'ID_LINGUA_LITERAT_ESPANHOL',
       'ID_LINGUA_LITERAT_OUTRA', 'ID_LINGUA_LITERAT_INDIGENA', 'ID_ARTES',
       'ID_EDUCACAO_FISICA', 'ID_HISTORIA', 'ID_GEOGRAFIA', 'ID_FILOSOFIA',
       'ID_ENSINO_RELIGIOSO', 'ID_ESTUDOS_SOCIAIS',
       'ID_INFORMATICA_COMPUTACAO', 'ID_PROFISSIONALIZANTE',
       'ID_DISC_ATENDIMENTO_ESPECIAIS', 'ID_DISC_DIVERSIDADE_SOCIO_CULT',
       'ID_LIBRAS', 'ID_DISCIPLINAS_PEDAG', 'ID_OUTRAS_DISCIPLINAS',
       'PK_COD_ENTIDADE', 'FK_COD_ESTADO', 'SIGLA', 'FK_COD_MUNICIPIO',
       'FK_COD_DISTRITO', 'ID_LOCALIZACAO', 'ID_DEPENDENCIA_ADM',
       'DESC_CATEGORIA_ESCOLA_PRIVADA', 'ID_CONVENIADA_PP',
       'ID_TIPO_CONVENIO_PODER_PUBLICO', 'ID_MANT_ESCOLA_PRIVADA_EMP',
       'ID_MANT_ESCOLA_PRIVADA_ONG', 'ID_MANT_ESCOLA_PRIVADA_SIND',
       'ID_MANT_ESCOLA_PRIVADA_S_FINS', 'ID_DOCUMENTO_REGULAMENTACAO',
       'ID_LOCALIZACAO_DIFERENCIADA', 'ID_EDUCACAO_INDIGENA'],
      dtype='object')

In [18]:
dados["2013.zip"].columns

Index(['ANO_CENSO', 'PK_COD_TURMA', 'NO_TURMA', 'HR_INICIAL',
       'HR_INICIAL_MINUTO', 'NU_DURACAO_TURMA', 'NUM_MATRICULAS',
       'FK_COD_MOD_ENSINO', 'FK_COD_ETAPA_ENSINO', 'FK_COD_CURSO_PROF',
       'FK_COD_TIPO_TURMA', 'ID_MAIS_EDUCACAO', 'ID_DIA_SEMANA_DOMINGO',
       'ID_DIA_SEMANA_SEGUNDA', 'ID_DIA_SEMANA_TERCA', 'ID_DIA_SEMANA_QUARTA',
       'ID_DIA_SEMANA_QUINTA', 'ID_DIA_SEMANA_SEXTA', 'ID_DIA_SEMANA_SABADO',
       'FK_COD_TIPO_ATIVIDADE_1', 'FK_COD_TIPO_ATIVIDADE_2',
       'FK_COD_TIPO_ATIVIDADE_3', 'FK_COD_TIPO_ATIVIDADE_4',
       'FK_COD_TIPO_ATIVIDADE_5', 'FK_COD_TIPO_ATIVIDADE_6', 'ID_BRAILLE',
       'ID_RECURSOS_BAIXA_VISAO', 'ID_PROCESSOS_MENTAIS',
       'ID_ORIENTACAO_MOBILIDADE', 'ID_SINAIS', 'ID_COM_ALT_AUMENT',
       'ID_ENRIQ_CURRICULAR', 'ID_SOROBAN', 'ID_INF_ACESSIVEL', 'ID_PORT_ESC',
       'ID_AUT_ESCOLAR', 'ID_QUIMICA', 'ID_FISICA', 'ID_MATEMATICA',
       'ID_BIOLOGIA', 'ID_CIENCIAS', 'ID_LINGUA_LITERAT_PORTUGUESA',
       'ID_LINGUA_LITERAT_INGLES', 'ID_LINGUA_LITERAT_ESPANHOL',
       'ID_LINGUA_LITERAT_FRANCES', 'ID_LINGUA_LITERAT_OUTRA',
       'ID_LINGUA_LITERAT_INDIGENA', 'ID_ARTES', 'ID_EDUCACAO_FISICA',
       'ID_HISTORIA', 'ID_GEOGRAFIA', 'ID_FILOSOFIA', 'ID_ENSINO_RELIGIOSO',
       'ID_ESTUDOS_SOCIAIS', 'ID_SOCIOLOGIA', 'ID_INFORMATICA_COMPUTACAO',
       'ID_PROFISSIONALIZANTE', 'ID_DISC_ATENDIMENTO_ESPECIAIS',
       'ID_DISC_DIVERSIDADE_SOCIO_CULT', 'ID_LIBRAS', 'ID_DISCIPLINAS_PEDAG',
       'ID_OUTRAS_DISCIPLINAS', 'PK_COD_ENTIDADE', 'FK_COD_ESTADO', 'SIGLA',
       'FK_COD_MUNICIPIO', 'FK_COD_DISTRITO', 'ID_LOCALIZACAO',
       'ID_DEPENDENCIA_ADM', 'DESC_CATEGORIA_ESCOLA_PRIVADA',
       'ID_CONVENIADA_PP', 'ID_TIPO_CONVENIO_PODER_PUBLICO',
       'ID_MANT_ESCOLA_PRIVADA_EMP', 'ID_MANT_ESCOLA_PRIVADA_ONG',
       'ID_MANT_ESCOLA_PRIVADA_SIST_S', 'ID_MANT_ESCOLA_PRIVADA_SIND',
       'ID_MANT_ESCOLA_PRIVADA_S_FINS', 'ID_DOCUMENTO_REGULAMENTACAO',
       'ID_LOCALIZACAO_DIFERENCIADA', 'ID_EDUCACAO_INDIGENA'],
      dtype='object')

In [19]:
dados["2015.zip"].columns

Index(['NU_ANO_CENSO', 'ID_TURMA', 'NO_TURMA', 'TX_HR_INICIAL',
       'TX_MI_INICIAL', 'NU_DURACAO_TURMA', 'NU_MATRICULAS',
       'TP_MEDIACAO_DIDATICO_PEDAGO', 'IN_ESPECIAL_EXCLUSIVA', 'IN_REGULAR',
       'IN_EJA', 'IN_PROFISSIONALIZANTE', 'TP_ETAPA_ENSINO',
       'CO_CURSO_EDUC_PROFISSIONAL', 'TP_TIPO_TURMA', 'IN_MAIS_EDUCACAO',
       'NU_DIAS_ATIVIDADE', 'IN_DIA_SEMANA_DOMINGO', 'IN_DIA_SEMANA_SEGUNDA',
       'IN_DIA_SEMANA_TERCA', 'IN_DIA_SEMANA_QUARTA', 'IN_DIA_SEMANA_QUINTA',
       'IN_DIA_SEMANA_SEXTA', 'IN_DIA_SEMANA_SABADO', 'CO_TIPO_ATIVIDADE_1',
       'CO_TIPO_ATIVIDADE_2', 'CO_TIPO_ATIVIDADE_3', 'CO_TIPO_ATIVIDADE_4',
       'CO_TIPO_ATIVIDADE_5', 'CO_TIPO_ATIVIDADE_6', 'IN_BRAILLE',
       'IN_RECURSOS_BAIXA_VISAO', 'IN_PROCESSOS_MENTAIS',
       'IN_ORIENTACAO_MOBILIDADE', 'IN_SINAIS', 'IN_COMUNICACAO_ALT_AUMENT',
       'IN_ENRIQ_CURRICULAR', 'IN_SOROBAN', 'IN_INFORMATICA_ACESSIVEL',
       'IN_PORT_ESCRITA', 'IN_AUTONOMIA_ESCOLAR', 'IN_DISC_QUIMICA',
       'IN_DISC_FISICA', 'IN_DISC_MATEMATICA', 'IN_DISC_BIOLOGIA',
       'IN_DISC_CIENCIAS', 'IN_DISC_LINGUA_PORTUGUESA',
       'IN_DISC_LINGUA_INGLES', 'IN_DISC_LINGUA_ESPANHOL',
       'IN_DISC_LINGUA_FRANCES', 'IN_DISC_LINGUA_INDIGENA',
       'IN_DISC_LINGUA_OUTRA', 'IN_DISC_ARTES', 'IN_DISC_EDUCACAO_FISICA',
       'IN_DISC_HISTORIA', 'IN_DISC_GEOGRAFIA', 'IN_DISC_FILOSOFIA',
       'IN_DISC_ENSINO_RELIGIOSO', 'IN_DISC_ESTUDOS_SOCIAIS',
       'IN_DISC_SOCIOLOGIA', 'IN_DISC_EST_SOCIAIS_SOCIOLOGIA',
       'IN_DISC_INFORMATICA_COMPUTACAO', 'IN_DISC_PROFISSIONALIZANTE',
       'IN_DISC_ATENDIMENTO_ESPECIAIS', 'IN_DISC_DIVER_SOCIO_CULTURAL',
       'IN_DISC_LIBRAS', 'IN_DISC_PEDAGOGICAS', 'IN_DISC_OUTRAS',
       'CO_ENTIDADE', 'CO_REGIAO', 'CO_MESORREGIAO', 'CO_MICRORREGIAO',
       'CO_UF', 'CO_MUNICIPIO', 'CO_DISTRITO', 'TP_DEPENDENCIA',
       'TP_LOCALIZACAO', 'TP_CATEGORIA_ESCOLA_PRIVADA', 'IN_CONVENIADA_PP',
       'TP_CONVENIO_PODER_PUBLICO', 'IN_MANT_ESCOLA_PRIVADA_EMP',
       'IN_MANT_ESCOLA_PRIVADA_ONG', 'IN_MANT_ESCOLA_PRIVADA_SIND',
       'IN_MANT_ESCOLA_PRIVADA_SIST_S', 'IN_MANT_ESCOLA_PRIVADA_S_FINS',
       'TP_REGULAMENTACAO', 'TP_LOCALIZACAO_DIFERENCIADA',
       'IN_EDUCACAO_INDIGENA'],
      dtype='object')

In [30]:
dados["2018.zip"].columns

Index(['NU_ANO_CENSO', 'ID_TURMA', 'NO_TURMA', 'TX_HR_INICIAL',
       'TX_MI_INICIAL', 'NU_DURACAO_TURMA', 'QT_MATRICULAS',
       'TP_MEDIACAO_DIDATICO_PEDAGO', 'IN_ESPECIAL_EXCLUSIVA', 'IN_REGULAR',
       'IN_EJA', 'IN_PROFISSIONALIZANTE', 'TP_ETAPA_ENSINO',
       'CO_CURSO_EDUC_PROFISSIONAL', 'TP_TIPO_TURMA', 'IN_MAIS_EDUCACAO',
       'NU_DIAS_ATIVIDADE', 'IN_DIA_SEMANA_DOMINGO', 'IN_DIA_SEMANA_SEGUNDA',
       'IN_DIA_SEMANA_TERCA', 'IN_DIA_SEMANA_QUARTA', 'IN_DIA_SEMANA_QUINTA',
       'IN_DIA_SEMANA_SEXTA', 'IN_DIA_SEMANA_SABADO', 'CO_TIPO_ATIVIDADE_1',
       'CO_TIPO_ATIVIDADE_2', 'CO_TIPO_ATIVIDADE_3', 'CO_TIPO_ATIVIDADE_4',
       'CO_TIPO_ATIVIDADE_5', 'CO_TIPO_ATIVIDADE_6', 'IN_BRAILLE',
       'IN_RECURSOS_BAIXA_VISAO', 'IN_PROCESSOS_MENTAIS',
       'IN_ORIENTACAO_MOBILIDADE', 'IN_SINAIS', 'IN_COMUNICACAO_ALT_AUMENT',
       'IN_ENRIQ_CURRICULAR', 'IN_SOROBAN', 'IN_INFORMATICA_ACESSIVEL',
       'IN_PORT_ESCRITA', 'IN_AUTONOMIA_ESCOLAR', 'IN_DISC_QUIMICA',
       'IN_DISC_FISICA', 'IN_DISC_MATEMATICA', 'IN_DISC_BIOLOGIA',
       'IN_DISC_CIENCIAS', 'IN_DISC_LINGUA_PORTUGUESA',
       'IN_DISC_LINGUA_INGLES', 'IN_DISC_LINGUA_ESPANHOL',
       'IN_DISC_LINGUA_FRANCES', 'IN_DISC_LINGUA_OUTRA',
       'IN_DISC_LINGUA_INDIGENA', 'IN_DISC_ARTES', 'IN_DISC_EDUCACAO_FISICA',
       'IN_DISC_HISTORIA', 'IN_DISC_GEOGRAFIA', 'IN_DISC_FILOSOFIA',
       'IN_DISC_ENSINO_RELIGIOSO', 'IN_DISC_ESTUDOS_SOCIAIS',
       'IN_DISC_SOCIOLOGIA', 'IN_DISC_EST_SOCIAIS_SOCIOLOGIA',
       'IN_DISC_INFORMATICA_COMPUTACAO', 'IN_DISC_PROFISSIONALIZANTE',
       'IN_DISC_ATENDIMENTO_ESPECIAIS', 'IN_DISC_DIVER_SOCIO_CULTURAL',
       'IN_DISC_LIBRAS', 'IN_DISC_PEDAGOGICAS', 'IN_DISC_OUTRAS',
       'CO_ENTIDADE', 'CO_REGIAO', 'CO_MESORREGIAO', 'CO_MICRORREGIAO',
       'CO_UF', 'CO_MUNICIPIO', 'CO_DISTRITO', 'TP_DEPENDENCIA',
       'TP_LOCALIZACAO', 'TP_CATEGORIA_ESCOLA_PRIVADA', 'IN_CONVENIADA_PP',
       'TP_CONVENIO_PODER_PUBLICO', 'IN_MANT_ESCOLA_PRIVADA_EMP',
       'IN_MANT_ESCOLA_PRIVADA_ONG', 'IN_MANT_ESCOLA_PRIVADA_SIND',
       'IN_MANT_ESCOLA_PRIVADA_SIST_S', 'IN_MANT_ESCOLA_PRIVADA_S_FINS',
       'TP_REGULAMENTACAO', 'TP_LOCALIZACAO_DIFERENCIADA',
       'IN_EDUCACAO_INDIGENA'],
      dtype='object')

In [ ]:
TP_MEDIACAO_DIDATICO_PEDAGO
TP_TIPO_ATENDIMENTO_TURMA

In [ ]:
IN_ESPECIAL_EXCLUSIVA = TP_MOD_ENSINO == 2
IN_DISC_EST_SOCIAIS_SOCIOLOGIA = IN_DISC_SOCIOLOGIA | IN_DISC_ESTUDOS_SOCIAIS

In [ ]:
IN_REGULAR	1,2,3,56,4,5,6,7,8,9,10,11,12,13,14, 15,16,17,18,19,20,21,22,23,24,41,25,26,27,28,29,30,31, 32,33,34,35,36,37 ou 38.
IN_EJA	Etapas consideradas (nas antigas modalidades 2 ou 3): TP_ETAPA_ENSINO igual a 65,67,69,70,71,72,73 ou 74.
IN_PROFISSIONALIZANTE	Etapas consideradas (nas antigas modalidades 1, 2 ou 3): TP_ETAPA_ENSINO igual a 30,31,32,33,34, 35,36,37,38,39,40,64,65,67,68,73 ou 74.

In [28]:
dados["2008.zip"].loc[lambda f: f["FK_COD_MOD_ENSINO"] == 1]

,ANO_CENSO,PK_COD_TURMA,NO_TURMA,HR_INICIAL,HR_INICIAL_MINUTO,NU_DURACAO_TURMA,NUM_MATRICULAS,FK_COD_MOD_ENSINO,FK_COD_ETAPA_ENSINO,FK_COD_CURSO_PROF,...,DESC_CATEGORIA_ESCOLA_PRIVADA,ID_CONVENIADA_PP,ID_TIPO_CONVENIO_PODER_PUBLICO,ID_MANT_ESCOLA_PRIVADA_EMP,ID_MANT_ESCOLA_PRIVADA_ONG,ID_MANT_ESCOLA_PRIVADA_SIND,ID_MANT_ESCOLA_PRIVADA_APAE,ID_DOCUMENTO_REGULAMENTACAO,ID_LOCALIZACAO_DIFERENCIADA,ID_EDUCACAO_INDIGENA
0,2008,6777713,4º D,13,0,250,24,1.0,17.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,0
1,2008,6777714,4º C,13,0,250,23,1.0,17.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,0
2,2008,6777716,4º B,7,0,250,33,1.0,17.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,0
3,2008,6777717,4º A,7,0,250,38,1.0,17.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,0
4,2008,6777719,3º D,13,0,250,18,1.0,16.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2198974,2008,9221724,5A,7,10,320,15,1.0,8.0,NaN,...,1.0,0.0,NaN,1.0,NaN,NaN,NaN,1,0,0
2198975,2008,9221725,6A,7,10,320,19,1.0,9.0,NaN,...,1.0,0.0,NaN,1.0,NaN,NaN,NaN,1,0,0
2198976,2008,9221726,8A,7,10,320,9,1.0,11.0,NaN,...,1.0,0.0,NaN,1.0,NaN,NaN,NaN,1,0,0
2198977,2008,9221727,3A,13,0,270,7,1.0,6.0,NaN,...,1.0,0.0,NaN,1.0,NaN,NaN,NaN,1,0,0
2198978,2008,9221728,1AA,13,0,270,7,1.0,2.0,NaN,...,1.0,0.0,NaN,1.0,NaN,NaN,NaN,1,0,0

In [29]:
dados["2013.zip"].loc[lambda f: f["FK_COD_MOD_ENSINO"] == 1]

,ANO_CENSO,PK_COD_TURMA,NO_TURMA,HR_INICIAL,HR_INICIAL_MINUTO,NU_DURACAO_TURMA,NUM_MATRICULAS,FK_COD_MOD_ENSINO,FK_COD_ETAPA_ENSINO,FK_COD_CURSO_PROF,...,ID_CONVENIADA_PP,ID_TIPO_CONVENIO_PODER_PUBLICO,ID_MANT_ESCOLA_PRIVADA_EMP,ID_MANT_ESCOLA_PRIVADA_ONG,ID_MANT_ESCOLA_PRIVADA_SIST_S,ID_MANT_ESCOLA_PRIVADA_SIND,ID_MANT_ESCOLA_PRIVADA_S_FINS,ID_DOCUMENTO_REGULAMENTACAO,ID_LOCALIZACAO_DIFERENCIADA,ID_EDUCACAO_INDIGENA
0,2013,3233601,FUND 1 AO 5 ANO - 4 G VESP,13,0,240,28,1.0,17.0,NaN,...,NaN,NaN,0,0,0,0,0,1,0,0
1,2013,362545,3º ANO TURMA B VESPERTINO,13,0,255,27,1.0,16.0,NaN,...,NaN,NaN,0,0,0,0,0,1,0,0
2,2013,3233602,FUND 1 AO 5 ANO - 4 H VESP,13,0,240,24,1.0,17.0,NaN,...,NaN,NaN,0,0,0,0,0,1,0,0
3,2013,362598,3º ANO TURMA C VESPERTINO,13,0,255,27,1.0,16.0,NaN,...,NaN,NaN,0,0,0,0,0,1,0,0
4,2013,3219190,FUND 1 AO 5 ANO - 5 A MAT,7,0,240,30,1.0,18.0,NaN,...,NaN,NaN,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2486520,2013,3375299,A006171107642,7,30,570,20,1.0,1.0,NaN,...,NaN,NaN,0,0,0,0,0,1,0,0
2486521,2013,3375300,A006171107667,7,30,570,26,1.0,1.0,NaN,...,NaN,NaN,0,0,0,0,0,1,0,0
2486522,2013,3375288,A006171107675,7,30,240,4,1.0,1.0,NaN,...,NaN,NaN,0,0,0,0,0,1,0,0
2486523,2013,3375301,AB06171107618,7,30,570,29,1.0,1.0,NaN,...,NaN,NaN,0,0,0,0,0,1,0,0
2486524,2013,3375302,AB06171107626,7,30,570,21,1.0,2.0,NaN,...,NaN,NaN,0,0,0,0,0,1,0,0

Verifica informações básicas de tamanho

In [22]:
dados["2020.zip"].shape

(188361, 83)

---

In [10]:
df = pd.read_parquet("dados/completo/aquisicao/censo_turma.parquet", filters=[("ANO", "=", 2020)])

In [11]:
df["TP_TIPO_LOCAL_TURMA"].value_counts()

NENHUM            2279985
SALA ANEXA          62141
PRISIONAL            4617
SOCIOEDUCATIVO       1883
Name: TP_TIPO_LOCAL_TURMA, dtype: int64

In [7]:
df.shape

(33357092, 73)